import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Sensor from '../../app/models/sensor.js'
import SmartDevice from '../../app/models/smart_device.js'
import { DateTime } from 'luxon'

interface SensorData {
  sensor_id: string
  name: string
  nom: string
  type: string
  value: string
  unit: string | null
  isAlert: boolean
  lastUpdate: DateTime
}

interface SensorsData {
  [key: string]: SensorData[]
}

export default class extends BaseSeeder {
  async run() {
    // Clear existing sensors
    await Sensor.query().delete()

    // Récupérer tous les devices
    const devices = await SmartDevice.all()

    // Vérifier si des devices existent
    if (devices.length === 0) {
      console.log('No devices found to attach sensors to')
      return
    }

    // Afficher les devices trouvés pour le debug
    console.log(
      'Found devices:',
      devices.map((d) => d.deviceSerial)
    )

    // Créer une map des devices pour un accès facile
    const deviceMap = new Map(devices.map((device) => [device.deviceSerial, device]))

    // Données des capteurs pour chaque device
    const sensorsData: SensorsData = {
      fct_1a2b3c4d: [
        {
          sensor_id: 'sen_hum_hang1',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '45',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_temp_hang1',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '22',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_pres_hang1',
          name: 'Pressure valve 3',
          nom: 'Pression soupape 3',
          type: 'pressure',
          value: '1013',
          unit: 'hPa',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_co2_hang1',
          name: 'Carbon dioxide',
          nom: 'Dioxyde de carbone',
          type: 'co2',
          value: '800',
          unit: 'ppm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_part_hang1',
          name: 'Particulate 2.5',
          nom: 'Particules 2.5',
          type: 'particulate',
          value: '12',
          unit: 'µg/m³',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_door_hang1',
          name: 'Main Door',
          nom: 'Porte principale',
          type: 'door',
          value: 'Closed',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_occ_hang1',
          name: 'People Count',
          nom: 'Nombre de personnes',
          type: 'occupancy',
          value: '12',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_smoke_hang1',
          name: 'Smoke Detector',
          nom: 'Détecteur de fumée',
          type: 'smoke',
          value: 'Normal',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_fan_hang1',
          name: 'Ventilation Fan',
          nom: 'Aération',
          type: 'fan',
          value: 'ON',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_noise_hang1',
          name: 'Noise Level',
          nom: 'Niveau sonore',
          type: 'noise',
          value: '75',
          unit: 'dB',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
      ],
      fct_5e6f7g8h: [
        {
          sensor_id: 'sen_hum_hang2',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '50',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_temp_hang2',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '23',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_pres_hang2',
          name: 'Pressure valve 1',
          nom: 'Pression soupape 1',
          type: 'pressure',
          value: '1015',
          unit: 'hPa',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_co2_hang2',
          name: 'Carbon dioxide',
          nom: 'Dioxyde de carbone',
          type: 'co2',
          value: '1200',
          unit: 'ppm',
          isAlert: true,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_part_hang2',
          name: 'Particulate 2.5',
          nom: 'Particules 2.5',
          type: 'particulate',
          value: '18',
          unit: 'µg/m³',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_door_hang2',
          name: 'Main Door',
          nom: 'Porte principale',
          type: 'door',
          value: 'Open',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_occ_hang2',
          name: 'People Count',
          nom: 'Nombre de personnes',
          type: 'occupancy',
          value: '15',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_smoke_hang2',
          name: 'Smoke Detector',
          nom: 'Détecteur de fumée',
          type: 'smoke',
          value: 'Normal',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_fan_hang2',
          name: 'Ventilation Fan',
          nom: 'Aération',
          type: 'fan',
          value: 'ON',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
        {
          sensor_id: 'sen_noise_hang2',
          name: 'Noise Level',
          nom: 'Niveau sonore',
          type: 'noise',
          value: '70',
          unit: 'dB',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:40:00Z'),
        },
      ],
      bld_5e4d3c2b: [
        {
          sensor_id: 'sen_temp_bld1',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '21',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
        {
          sensor_id: 'sen_hum_bld1',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '55',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
        {
          sensor_id: 'sen_water_bld1',
          name: 'Water Level',
          nom: "Niveau d'eau",
          type: 'water_level',
          value: '4.2',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
        {
          sensor_id: 'sen_wind_bld1',
          name: 'Wind Speed',
          nom: 'Vitesse du vent',
          type: 'wind',
          value: '28',
          unit: 'km/h',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
        {
          sensor_id: 'sen_vis_bld1',
          name: 'Visibility',
          nom: 'Visibilité',
          type: 'visibility',
          value: '4500',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
        {
          sensor_id: 'sen_noise_bld1',
          name: 'Noise Level',
          nom: 'Niveau sonore',
          type: 'noise',
          value: '72',
          unit: 'dB',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
        {
          sensor_id: 'sen_wave_bld1',
          name: 'Wave Height',
          nom: 'Hauteur des vagues',
          type: 'wave_height',
          value: '1.5',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
        {
          sensor_id: 'sen_door_bld1',
          name: 'Main Entrance',
          nom: 'Entrée principale',
          type: 'door',
          value: 'Closed',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:30:00Z'),
        },
      ],
      bld_dock456: [
        {
          sensor_id: 'sen_temp_dock1',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '19',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:52:00Z'),
        },
        {
          sensor_id: 'sen_hum_dock1',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '60',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:52:00Z'),
        },
        {
          sensor_id: 'sen_door_dock1',
          name: 'Dock Door',
          nom: 'Porte du dock',
          type: 'door',
          value: 'Open',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T14:52:00Z'),
        },
      ],
      fct_9i8h7g6f: [
        {
          sensor_id: 'sen_temp_hang3',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '20',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_hum_hang3',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '65',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_pres_hang3',
          name: 'Pressure valve 4',
          nom: 'Pression soupape 4',
          type: 'pressure',
          value: '1012',
          unit: 'hPa',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_co2_hang3',
          name: 'Carbon dioxide',
          nom: 'Dioxyde de carbone',
          type: 'co2',
          value: '750',
          unit: 'ppm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_part_hang3',
          name: 'Particulate 2.5',
          nom: 'Particules 2.5',
          type: 'particulate',
          value: '10',
          unit: 'µg/m³',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_door_hang3',
          name: 'Main Door',
          nom: 'Porte principale',
          type: 'door',
          value: 'Closed',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_occ_hang3',
          name: 'People Count',
          nom: 'Nombre de personnes',
          type: 'occupancy',
          value: '5',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_smoke_hang3',
          name: 'Smoke Detector',
          nom: 'Détecteur de fumée',
          type: 'smoke',
          value: 'Normal',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_fan_hang3',
          name: 'Ventilation Fan',
          nom: 'Aération',
          type: 'fan',
          value: 'OFF',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
        {
          sensor_id: 'sen_noise_hang3',
          name: 'Noise Level',
          nom: 'Niveau sonore',
          type: 'noise',
          value: '45',
          unit: 'dB',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T12:30:00Z'),
        },
      ],
      bld_9a8b7c6: [
        {
          sensor_id: 'sen_temp_bld2',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '22',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_hum_bld2',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '50',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_co2_bld2',
          name: 'Carbon dioxide',
          nom: 'Dioxyde de carbone',
          type: 'co2',
          value: '600',
          unit: 'ppm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_stock_bld2',
          name: 'Stock Level',
          nom: 'Niveau de stock',
          type: 'stock',
          value: '75',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_motion_bld2',
          name: 'Motion Detection',
          nom: 'Détection de mouvement',
          type: 'motion',
          value: 'Active',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_light_bld2',
          name: 'Light Level',
          nom: 'Niveau de luminosité',
          type: 'light',
          value: '800',
          unit: 'lux',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_vib_bld2',
          name: 'Vibration',
          nom: 'Vibration',
          type: 'vibration',
          value: '0.2',
          unit: 'g',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_air_bld2',
          name: 'Air Quality',
          nom: "Qualité de l'air",
          type: 'air_quality',
          value: 'Good',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_water_bld2',
          name: 'Water Level',
          nom: "Niveau d'eau",
          type: 'water_level',
          value: '3.5',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_wind_bld2',
          name: 'Wind Speed',
          nom: 'Vitesse du vent',
          type: 'wind',
          value: '25',
          unit: 'km/h',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_vis_bld2',
          name: 'Visibility',
          nom: 'Visibilité',
          type: 'visibility',
          value: '5000',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_noise_bld2',
          name: 'Noise Level',
          nom: 'Niveau sonore',
          type: 'noise',
          value: '65',
          unit: 'dB',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
        {
          sensor_id: 'sen_wave_bld2',
          name: 'Wave Height',
          nom: 'Hauteur des vagues',
          type: 'wave_height',
          value: '1.2',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:10:00Z'),
        },
      ],
      bld_1a2b3c4d: [
        {
          sensor_id: 'sen_temp_bld3',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '23',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
        {
          sensor_id: 'sen_hum_bld3',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '45',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
        {
          sensor_id: 'sen_occ_bld3',
          name: 'People Count',
          nom: 'Nombre de personnes',
          type: 'occupancy',
          value: '8',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
        {
          sensor_id: 'sen_water_bld3',
          name: 'Water Level',
          nom: "Niveau d'eau",
          type: 'water_level',
          value: '3.2',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
        {
          sensor_id: 'sen_wind_bld3',
          name: 'Wind Speed',
          nom: 'Vitesse du vent',
          type: 'wind',
          value: '20',
          unit: 'km/h',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
        {
          sensor_id: 'sen_vis_bld3',
          name: 'Visibility',
          nom: 'Visibilité',
          type: 'visibility',
          value: '6000',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
        {
          sensor_id: 'sen_noise_bld3',
          name: 'Noise Level',
          nom: 'Niveau sonore',
          type: 'noise',
          value: '60',
          unit: 'dB',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
        {
          sensor_id: 'sen_wave_bld3',
          name: 'Wave Height',
          nom: 'Hauteur des vagues',
          type: 'wave_height',
          value: '0.8',
          unit: 'm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:05:00Z'),
        },
      ],
      lab_research_tls001: [
        {
          sensor_id: 'sen_temp_lab',
          name: 'Temperature',
          nom: 'Température',
          type: 'temperature',
          value: '21.5',
          unit: '°C',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_hum_lab',
          name: 'Humidity',
          nom: 'Humidité',
          type: 'humidity',
          value: '45',
          unit: '%',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_co2_lab',
          name: 'Carbon dioxide',
          nom: 'Dioxyde de carbone',
          type: 'co2',
          value: '450',
          unit: 'ppm',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_air_lab',
          name: 'Air Quality',
          nom: "Qualité de l'air",
          type: 'air_quality',
          value: 'Excellent',
          unit: null,
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_pres_lab',
          name: 'Pressure',
          nom: 'Pression',
          type: 'pressure',
          value: '1013.25',
          unit: 'hPa',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_rad_lab',
          name: 'Radiation Level',
          nom: 'Niveau de radiation',
          type: 'radiation',
          value: '0.12',
          unit: 'µSv/h',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_noise_lab',
          name: 'Noise Level',
          nom: 'Niveau sonore',
          type: 'noise',
          value: '35',
          unit: 'dB',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_part25_lab',
          name: 'Particulate 2.5',
          nom: 'Particules 2.5',
          type: 'particulate',
          value: '8',
          unit: 'µg/m³',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
        {
          sensor_id: 'sen_part10_lab',
          name: 'Particulate 10',
          nom: 'Particules 10',
          type: 'particulate',
          value: '15',
          unit: 'µg/m³',
          isAlert: false,
          lastUpdate: DateTime.fromISO('2024-03-20T15:30:00Z'),
        },
      ],
    }

    // Afficher les clés de la map pour le debug
    console.log('Device map keys:', Array.from(deviceMap.keys()))

    // Créer les capteurs pour chaque device
    for (const [deviceSerial, sensors] of Object.entries(sensorsData)) {
      const device = deviceMap.get(deviceSerial)
      if (!device) continue

      await Promise.all(
        sensors.map((sensorData) =>
          Sensor.create({
            smartDeviceId: device.id.toString(),
            ...sensorData,
          })
        )
      )
    }
  }
}
